---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: tap caskroom/cloudfoundry
  homebrew_tap: tap=cloudfoundry/tap state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - ansible
    - ansible-cmdb
    - asciidoc
    - asciinema
    - autoconf
    - automake
    - awscli
    - bash
    - bash-completion
    - bats
    - bfg
    - bind
    - binutils
    - cf-cli
    - cloud-watch
    - cmake
    - corectl
    - coreutils
    - curl
    - diffutils
    - direnv
    - dirmngr
    - dnsmasq
    - dnsperf
    - dnstracer
    - docbook
    - elixir
    - elm
    - erlang
    - etcd
    - fdupes
    - ffmpeg --with-fac
    - figlet
    - file-formula
    - findutils --with-default-names
    - fleetctl
    - fontconfig
    - freetype
    - gawk
    - geoip
    - gettext
    - ghostscript
    - git
    - git-extras
    - git-flow
    - git-secrets
    - giter8
    - github-release
    - gnu-indent --with-default-names
    - gnu-sed --with-default-names
    - gnu-tar --with-default-names
    - gnu-which --with-default-names
    - gnupg2
    - gnutls
    - go
    - godep
    - gpatch
    - gpg-agent
    - grafana
    - graphviz
    - grep --with-default-names
    - gzip
    - htop
    - httpie
    - httpstat
    - hugo
    - icu4c
    - jid
    - jpeg
    - jq
    - kibana
    - kube-aws
    - kubernetes-cli
    - kubernetes-helm
    - lame
    - less
    - liquibase
    - lynx
    - m4
    - make
    - mkdocs
    - moreutils
    - mycli
    - neovim
    - nmap
    - node
    - oniguruma
    - openssh
    - openssl
    - packer
    - pandoc
    - prometheus
    - pssh
    - pv
    - pwgen
    - pyenv
    - pyenv-virtualenv
    - pyenv-virtualenvwrapper
    - pypy3
    - python
    - python3
    - rbenv
    - readline
    - rename
    - rsync
    - ruby-build
    - s3cmd
    - sbt
    - scala
    - screen
    - slackcat
    - socat
    - sphinx-doc
    - spiff
    - ssh-copy-id
    - sshfs
    - tcptrace
    - terminal-notifier
    - terraform
    - tmux
    - tree
    - unzip
    - vault
    - watch
    - wdiff
    - webkit2png
    - webp
    - wget
    - wireshark
    - xvid
    - zlib
    - zsh
    - zsh-completions

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - adium
    - atom
    - chefdk
    - clipmenu
    - etcher
    - evernote
    - flux
    - geppetto
    - github
    - google-chrome
    - handbrake
    - handbrake-cli
    - imageoptim
    - intellij-idea-ce
    - jxplorer
    - launchcontrol
    - ngrok
    - pgadmin4
    - psequel
    - pycharm-ce
    - qlcolorcode
    - qlmarkdown
    - qlstephen
    - quicklook-json
    - screenhero
    - sequel-pro
    - skype
    - slack
    - squidman
    - torbrowser
    - transmission
    - utorrent
    - vagrant
    - vagrant-manager
    - virtualbox
    - virtualbox-extension-pack
    - wercker
    - xmind
